SELECT empno,
       ename,
	   sal
  FROM emp
;  

--     EMPNO ENAME                       SAL
------------ -------------------- ----------
--      7369 SMITH                       800
--      7499 ALLEN                      1600
--      7521 WARD                       1250
--      7566 JONES                      2975
--      7654 MARTIN                     1250
--      7698 BLAKE                      2850
--      7782 CLARK                      2450
--      7788 SCOTT                      3000
--      7839 KING                       5000
--      7844 TURNER                     1500
--      7900 JAMES                       950
--      7902 FORD                       3000
--      7934 MILLER                     1300
--
--13 행이 선택되었습니다.